<?php

/***************************************************************************
      This file was automatically generated by Admin FAQ Editor
 ***************************************************************************/

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/

// 
// To add an entry to your FAQ simply add a line to this file in this format:
// $faq[] = array("question", "answer");
// If you want to separate a section enter $faq[] = array("--","Block heading goes here if wanted");
// Links will be created automatically
//
// DO NOT forget the ; at the end of the line.
// Do NOT put double quotes (") in your FAQ entries, if you absolutely must then escape them ie. \"something\"
//
// The FAQ items will appear on the FAQ page in the same order they are listed in this file
//

$faq[] = array("--", "Concepts généraux");
$faq[] = array("Où se trouve \"l'accès admin\" ?", "Elle n'existe plus !
<br />
<br />En effet, alors que dans famille 2 vous deviez vous rendre sur un lien caché pour administrer votre rubrique, dans famille 3 l'administration de votre rubrique se fait directement dans votre rubrique !
<br />
<br />Identifiez-vous et vous devriez voir les liens/formulaires nécessaires à l'administration de votre rubrique. Si ce n'est pas le cas, contactez Boris ou Flo.");



?>